stages:
  - upload


upload chart:
  stage: upload
  image: ubuntu:22.04
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    # Set up utils and get iam token
    - apt update && apt install -y curl
    - wget -O get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod +x ./get_helm.sh && ./get_helm.sh
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - echo $YC_AUTH_KEY_JSON | base64 --decode > ./key.json
    - ~/yandex-cloud/bin/yc config profile create admin
    - ~/yandex-cloud/bin/yc config set service-account-key key.json
    - export YC_IAM_TOKEN=$(~/yandex-cloud/bin/yc iam create-token)

    # Package helm chart and push it to registry
    - helm registry login cr.yandex -u iam -p $YC_IAM_TOKEN
    - helm package --version $CI_COMMIT_TAG ./
    - ls
