clusterip:
  port: 80
  targetPort: http

lockboxSecretStore:
  enabled: false

deployment:
  replicaCount: 1
  containerPort: 8080

  resources:
    requests:
      memory: "400Mi"
      cpu: "50m"
    limits:
      memory: "600Mi"
      cpu: "200m"

  readinessProbe:
    enabled: false

ingress:
  enabled: true
  websocketSupport: true

    