lockboxSecretStore:
  enabled: true
  externalSecret:
    secretId: ""
    data: {}

certificateSecretStore:
  enabled: true
  externalSecret:
    certificateId: ""

clusterip:
  ports:
  # Port that you want to be used for ingress
  # shold be first!
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

deployment:
  replicaCount: 1
  image: ""
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env: {}
  readinessProbe:
    enabled: false
    data:
      httpGet:
        path: /actuator/health
        port: http
      initialDelaySeconds: 50
      periodSeconds: 10


  resources:
    requests:
      cpu: "150m"
      memory: "400Mi"
    limits:
      cpu: "250m"
      memory: "600Mi"

ingress:
  enabled: true
  host: ""
