{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    version: 0.1.7
    {{- if .Values.ingress.websocketSupport -}}
    {{- include "ingress.websocketSupport" . | nindent 4 }}
    {{- end }}

spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-certificate-secret
  ingressClassName: {{ .Release.Name }}-class-resource
  rules:
    {{- with (index .Values.clusterip.ports 0) }}
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Release.Name }}
              port:
                name: {{ .name }}
      {{- end }}
{{- end }}
